### PR TITLE
Update ovirt_image_template.yml

### PR DESCRIPTION
**Pull request by johnsimcall**
Provide an example of using a file:/// URI

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by johnsimcall** [comment]
Hi @machacekondra, would you consider this example helpful to new users?

**Comment by machacekondra** [comment]
Of course. Thank you. Even better would be if it's also here:

 https://github.com/oVirt/ovirt-ansible-image-template/blob/master/README.md#role-variables

and here:

 https://github.com/oVirt/ovirt-ansible-image-template/blob/master/README.md#example-playbook

**Comment by mnecas** [comment]
I have created similar PR to resolve this and add another example https://github.com/oVirt/ovirt-ansible-image-template/pull/68.

**Pull request closed without merging**
